services:
   web:
      image: ghcr.io/okuru-id/money-tracker-fe:latest
      container_name: mt-frontend
      build:
         context: .
         dockerfile: Dockerfile
         args:
            VITE_API_BASE_URL: ${VITE_API_BASE_URL:-}
            VITE_APP_BASE_URL: ${VITE_APP_BASE_URL:-}
      networks:
         - be_default
      ports:
         - "4173:80"
      extra_hosts:
         - "host.docker.internal:host-gateway"
      restart: unless-stopped

networks:
   be_default:
      external: true
